[custom]
;https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/config/ACL4SSR_Online_Full.ini
;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml
;acl4SSR规则

;去广告：支持 but disabled
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持
;DNS泄漏：支持 ((a)clash配置里面不要绕过大陆IP (b)ruleset=全球直连,[]GEOIP,CN 后面加上“,no-resolve”)

;1、域名规则设置
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
;ruleset=广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
;ruleset=应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=微软Bing,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=OpenAi,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
;ruleset=网易音乐,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
;ruleset=游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
;ruleset=游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
;ruleset=游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
;ruleset=游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
;ruleset=游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
;ruleset=奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
;ruleset=巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
;ruleset=哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
;ruleset=哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🔰 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
;ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=全球直连,[]GEOIP,LAN
ruleset=全球直连,[]GEOSITE,CN
ruleset=🔰 节点选择,[]GEOSITE,geolocation-!cn
ruleset=全球直连,[]GEOIP,CN,no-resolve
ruleset=漏网之鱼,[]FINAL

;2、策略组（域名组-节点组）
custom_proxy_group=🔰 节点选择`select`[]所有-自动`[]DIRECT`[]REJECT`[]手动切换`[]港日-自动`[]港日新-自动`[]港台日新韩-自动`[]台日新韩-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]美国-自动`[]其他-自动`[]故障转移`[]负载均衡
custom_proxy_group=手动切换`select`[]美国-自动
custom_proxy_group=电报消息`select`[]🔰 节点选择`[]DIRECT`[]REJECT`[]手动切换`[]所有-自动`[]港台日新韩-自动`[]台日新韩-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]美国-自动`[]其他-自动`[]故障转移`[]负载均衡
custom_proxy_group=OpenAi`select`[]🔰 节点选择`[]DIRECT`[]REJECT`[]手动切换`[]所有-自动`[]港台日新韩-自动`[]台日新韩-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]美国-自动`[]其他-自动`[]故障转移`[]负载均衡
custom_proxy_group=油管视频`select`[]🔰 节点选择`[]DIRECT`[]REJECT`[]手动切换`[]所有-自动`[]港台日新韩-自动`[]台日新韩-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]美国-自动`[]其他-自动`[]故障转移`[]负载均衡
custom_proxy_group=奈飞视频`select`[]🔰 节点选择`[]奈飞节点`[]DIRECT`[]REJECT`[]手动切换`[]所有-自动`[]港台日新韩-自动`[]台日新韩-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]美国-自动`[]其他-自动`[]故障转移`[]负载均衡
custom_proxy_group=巴哈姆特`select`[]台湾-自动`[]🔰 节点选择`[]手动切换`[]DIRECT
custom_proxy_group=哔哩哔哩`select`[]全球直连`[]台湾-自动`[]香港-自动
custom_proxy_group=国外媒体`select`[]🔰 节点选择`[]DIRECT`[]REJECT`[]手动切换`[]所有-自动`[]港台日新韩-自动`[]台日新韩-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]美国-自动`[]其他-自动`[]故障转移`[]负载均衡
custom_proxy_group=微软Bing`select`[]🔰 节点选择`[]DIRECT`[]REJECT`[]手动切换`[]所有-自动`[]港台日新韩-自动`[]台日新韩-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]美国-自动`[]其他-自动`[]故障转移`[]负载均衡
custom_proxy_group=国内媒体`select`[]DIRECT`[]香港-自动`[]台湾-自动`[]新加坡-自动`[]日本-自动`[]手动切换
custom_proxy_group=谷歌FCM`select`[]🔰 节点选择`[]DIRECT`[]美国-自动`[]香港-自动`[]台湾-自动`[]新加坡-自动`[]日本-自动`[]韩国-自动`[]手动切换
custom_proxy_group=微软云盘`select`[]DIRECT`[]🔰 节点选择`[]美国-自动`[]香港-自动`[]台湾-自动`[]新加坡-自动`[]日本-自动`[]韩国-自动`[]手动切换
custom_proxy_group=微软服务`select`[]DIRECT`[]🔰 节点选择`[]美国-自动`[]香港-自动`[]台湾-自动`[]新加坡-自动`[]日本-自动`[]韩国-自动`[]手动切换
custom_proxy_group=苹果服务`select`[]DIRECT`[]🔰 节点选择`[]美国-自动`[]香港-自动`[]台湾-自动`[]新加坡-自动`[]日本-自动`[]韩国-自动`[]手动切换
custom_proxy_group=游戏平台`select`[]DIRECT`[]🔰 节点选择`[]美国-自动`[]香港-自动`[]台湾-自动`[]新加坡-自动`[]日本-自动`[]韩国-自动`[]手动切换
custom_proxy_group=网易音乐`select`[]DIRECT`[]🔰 节点选择`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=全球直连`select`[]DIRECT`[]🔰 节点选择
custom_proxy_group=广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=漏网之鱼`select`[]DIRECT`[]REJECT`[]手动切换`[]🔰 节点选择`[]所有-自动`[]港台日新韩-自动`[]台日新韩-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]美国-自动`[]其他-自动`[]故障转移`[]负载均衡

;3、节点组
custom_proxy_group=所有-自动`url-test`.*`https://www.gstatic.com/generate_204`120,,30
custom_proxy_group=港日-自动`url-test`(广港|香港|港|HK|hk|Hong Kong|🇭🇰|HongKong|hongkong|广日|日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan)`https://www.gstatic.com/generate_204`120,,30
custom_proxy_group=港日新-自动`url-test`(广港|香港|港|HK|hk|Hong Kong|🇭🇰|HongKong|hongkong|广日|日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan|广新|新加坡|SG|坡|狮城|🇸🇬|Singapore)`https://www.gstatic.com/generate_204`120,,30
custom_proxy_group=香港-自动`url-test`(广港|香港|港|HK|hk|Hong Kong|🇭🇰|HongKong|hongkong)`https://www.gstatic.com/generate_204`120,,30
custom_proxy_group=日本-自动`url-test`(广日|日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan)`https://www.gstatic.com/generate_204`120,,30
custom_proxy_group=新加坡-自动`url-test`(广新|新加坡|SG|坡|狮城|🇸🇬|Singapore)`https://www.gstatic.com/generate_204`120,,30
custom_proxy_group=台湾-自动`url-test`(广台|台湾|台灣|台|新北|彰化|TW|Tai Wan|🇹🇼|🇨🇳|TaiWan|Taiwan)`https://www.gstatic.com/generate_204`120,,30
custom_proxy_group=韩国-自动`url-test`(广韩|韩国|韓國|KR|首尔|春川|🇰🇷|Korea|KOR|韩|韓)`https://www.gstatic.com/generate_204`120,,30
custom_proxy_group=美国-自动`url-test`(广美|美|US|纽约|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|🇺🇸|United States)`https://www.gstatic.com/generate_204`120,,30
custom_proxy_group=其他-自动`url-test`(波|柬|斯|尼|也|克|比|尔|立|冰|秘|耳|利|埃|希|斯|孟|芬|阿|愛|澳|英|德|南|意|法|拿|墨|印|越|俄|瑞|智|荷|比|巴|沙|班|泰|德|烏|以|Australia|Konghwaguk)`https://www.gstatic.com/generate_204`120,,30
custom_proxy_group=港台新韩-自动`url-test`(广港|香港|港|HK|hk|Hong Kong|🇭🇰|HongKong|hongkong|广台|台湾|台灣|台|新北|彰化|TW|Tai Wan|🇹🇼|🇨🇳|TaiWan|Taiwan|广新|新加坡|SG|坡|狮城|🇸🇬|Singapore|广韩|韩国|韓國|KR|首尔|春川|🇰🇷|Korea|KOR|韩|韓)`https://www.gstatic.com/generate_204`120,,30
custom_proxy_group=台日新韩-自动`url-test`(广台|台湾|台灣|台|新北|彰化|TW|Tai Wan|🇹🇼|🇨🇳|TaiWan|Taiwan|广日|日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan|广新|新加坡|SG|坡|狮城|🇸🇬|Singapore|广韩|韩国|韓國|KR|首尔|春川|🇰🇷|Korea|KOR|韩|韓)`https://www.gstatic.com/generate_204`120,,30
custom_proxy_group=港台日新韩-自动`url-test`(广港|香港|港|HK|hk|Hong Kong|🇭🇰|HongKong|hongkong|广台|台湾|台灣|台|新北|彰化|TW|Tai Wan|🇹🇼|🇨🇳|TaiWan|Taiwan|广日|日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan|广新|新加坡|SG|坡|狮城|🇸🇬|Singapore|广韩|韩国|韓國|KR|首尔|春川|🇰🇷|Korea|KOR|韩|韓)`https://www.gstatic.com/generate_204`120,,30
custom_proxy_group=奈飞节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media)
custom_proxy_group=故障转移`fallback`.*`https://www.gstatic.com/generate_204`180
custom_proxy_group=负载均衡`load-balance`.*`https://www.gstatic.com/generate_204`180
custom_proxy_group=Proxy`select`[]港台新韩-自动`[]DIRECT`[]REJECT`[]手动切换`[]🔰 节点选择`[]所有-自动`[]港台日新韩-自动`[]台日新韩-自动`[]港日-自动`[]港日新-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]美国-自动`[]其他-自动`[]故障转移`[]负载均衡

;4、启用规则集
enable_rule_generator=true
overwrite_original_rules=true
